# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Updater LLC.
subtitle: A website for Updater LLC.
description: We are software developer company who supports your Changes and Growth.
keywords: Software Engineering,Agile Development
author: Updater LLC.
language: ja
timezone: Japan

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.updater.cc
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
email: hello@updater.cc

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape

theme: beautiful-hexo

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# hexo-deployer-s3
## https://github.com/nt3rp/hexo-deployer-s3
deploy:
  type: s3
  bucket: <S3 bucket>
  aws_key: <AWS id key>
  aws_secret: <AWS secret key>
  concurrency: 2
  region: <region>

# hexo-autonofollow
## https://github.com/liuzc/hexo-autonofollow
nofollow:
  enable: true

# Hexo-all-minifier
## https://github.com/unhealthy/hexo-all-minifier
html_minifier:
  enable: true
  exclude:

css_minifier:
  enable: true
  exclude:
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# hexo-auto-canonical
## Add an auto canonical helper simply to your html's <head> block as follows:
##  <%- autoCanonical(config, page) %>

# hexo-autolinker
## https://github.com/klugjo/hexo-autolinker
autolinker:
  enable: true
  newWindow: true
  urls: true
  email: true
  tel: true
  twitter: true
  hashtag: instagram
  className: 'autolinked'

# hexo-github-card
## https://github.com/Gisonrg/hexo-github-card
## {% githubCard user [repo] [width = 400] [theme] [client_id] [client_secret] %}

#__END__
